version: '3.8'

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: smarttbot
      MYSQL_ROOT_PASSWORD: smarttbot
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    ports:
      - 33066:3306
    networks:
      smarttbotNetWork:
        ipv4_address: 172.26.0.2

  python:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - .:/app
    networks:
      smarttbotNetWork:
        ipv4_address: 172.26.0.3
    depends_on:
      - db

networks:
  smarttbotNetWork:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.26.0.0/16